### ISSUE TITLE
Navbar - Login/User Profile button

### ISSUE THREAD

**Issue by Zane-L-B-O** [jrs-coding-school/fall-2023-group-project#13]
As a new unregistered user I want to see a button on a navigation bar that take me to the login page, so that I can make an account.

- [x] Create a button on the navbar to send the user to the login page if they're not logged in
- [x] If the user doesn't have an account take them to registration page
- [x] If they have an account and log in take the to the Home page

As a logged in user I want to see a button that takes me to my profile settings, so that I can customize my profile.

- [x] check to see if the user is logged in change to user profile button
- [x] when user clicks on button take user to profile page

As a logged in user I want to see a button that logs me out of my account, so that I can secure my credentials.

- [x] when user profile button is clicked take user to the profile page 
- [x] when user clicks logout button it logs out the user then redirects to home page

![image](https://github.com/jrs-coding-school/fall-2023-group-project/assets/144725938/77d4061a-f88b-4b28-aa58-647b850f4c99)

**Comment by Amin-JRS** [comment]
Includes feature #5
