### ISSUE TITLE
Navbar - Navigation Buttons

### ISSUE THREAD

**Issue by Zane-L-B-O** [jrs-coding-school/fall-2023-group-project#18]
As a user I want to see a Home button that takes me to the home page so I can see all the currently available card games and pick which one I play.

- [ ] Place holder

As a user I want to see a button that takes me to the card catalog page so that I can see all cards for a card game.

- [x] Cards Catalogue button

As a logged in user I want to see a button that takes me to my card collection so that I can see all cards I own.

- [x] Collection button

As a user I want to see a button that takes me to the deck list page so that I can see popular decks and create my own decks.

- [x] Decks button

As a user I want to see a button that takes me to the guides page so that I can see popular guides and create my own guides.

- [x] Guides Button

As a user I want to see a button that takes me to the rules page so that I can see the rules and formats for a card game.

- [x] Rules button

As a user I want to see a button that takes me to the news page so that I can see the latest news about the card game.
- [x] News button

![image](https://github.com/jrs-coding-school/fall-2023-group-project/assets/144725938/77d4061a-f88b-4b28-aa58-647b850f4c99)

![image](https://github.com/jrs-coding-school/fall-2023-group-project/assets/144725938/15c7c503-aad1-4c38-ab56-31016b715d17)

**Comment by Amin-JRS** [comment]
Include #13 in this branch
